from pathlib import Path
import csv,json,collections,re
out=Path(__file__).resolve().parents[1]/'docs/audit'
out.mkdir(parents=True,exist_ok=True)
rows=[]
def add(group,feature,status,original,ios,gap,phase='2',accept='اختبار التدفق على الآيباد في الاتجاهين ومقارنة الحالة المقابلة في الأصل',dependency='محلي'):
 rows.append(dict(id=f'F{len(rows)+1:03}',group=group,feature=feature,status=status,original_evidence=original,ios_evidence=ios,gap=gap,phase=phase,dependency=dependency,acceptance=accept,visual_parity='غير مصدّقة؛ الهوية تتغير لكن ترتيب الأدوات والسلوك يحتاجان مقارنة مستقلة'))
A=add
A('الحساب والبداية','الترحيب وهوية Cookies والشاشة الكاملة','موجود','ui/dashboard/SplashActivity.java؛ لقطة 01-original-launch','App/UI/WelcomeView.swift؛ لقطات المحاكيات','هوية جديدة مقصودة؛ الأصل واجهة دخول Google وليست ترحيب Cookies','0')
A('الحساب والبداية','الدخول بالبريد وكلمة المرور','موجود','إعدادات auth الأصلية؛ اختبار البريد المؤقت','App/Services/ReferenceService.swift؛ تجربة المستخدم اليدوية','نجح المستخدم؛ يحتاج حفظ الجلسة وانتهاء الصلاحية وانقطاع الشبكة لاختبارات إضافية','0')
A('الحساب والبداية','إنشاء الحساب والتأكيد وإعادة إرسال التأكيد','جزئي','/auth/v1/signup وresend؛ رسالة الاختبار وصلت','App/UI/AccountView.swift؛ docs/auth-verification-2026-10-09.json','إنشاء/تأكيد اختُبرا HTTP؛ إعادة الإرسال واجهة فعلية لم تختبر على جهاز؛ رابط التأكيد يعود localhost','0',dependency='إعدادات البريد وعنوان العودة لدى مالك الخدمة')
A('الحساب والبداية','الدخول باستخدام Google والعودة إلى التطبيق','اعتماد خادم','العميل الأصلي يستخدم Google ID token؛ صورة المستخدم localhost','ReferenceService.google؛ web PKCE','لم يثبت نجاح Google؛ قبول cookies-editor://auth/callback أو تسجيل عميل iOS رسمي مطلوب','0',dependency='تهيئة OAuth وRedirect لدى المالك')
A('الحساب والبداية','الخروج وحفظ الجلسة وتجديدها','جزئي','دخول/خروج ومستودعات الخدمة في APK','Keychain وrefresh/logout في ReferenceService','الكود موجود؛ دورة انتهاء جلسة/تجديد كاملة على الجهاز غير موثقة','0')
A('الحساب والبداية','ربط Discord وعرض الحساب المرتبط','ناقص','dialog_discord_link؛ dashboard؛ strings discord','—','واجهة الربط والعودة والتحقق من الحساب غير موجودة','6',dependency='خدمة ربط Discord الرسمية')
A('الحساب والبداية','الشرح الأولي وبطاقات التدريب','ناقص','layout_tutorial_card_simple؛ Prefs tutorial flags','—','خطوات تدريب التايبر/المحرر الأصلية غير موجودة','5')
A('المشاريع والصفحات','المعرض والمجلدات المتداخلة والبحث المحلي','موجود','ProjectsActivity؛ ProjectGalleryActivity؛ لقطتا 03 و10','LibraryView؛ LibraryStore؛ اختبارات المجلدات','التنظيم المحلي موجود؛ لا يساوي تلقائيًا نموذج المشروع متعدد الصفحات','1')
A('المشاريع والصفحات','إعادة تسمية ونقل وحذف الأعمال','موجود','dialog_project_options؛ dialog_page_options','LibraryView contextMenu؛ LibraryStore','يلزم مطابقة الحوار وشروط الحذف والصلاحيات لكل مستوى','1')
A('المشاريع والصفحات','مشروع واحد يحتوي فصلًا بصفحات مرتبة','ناقص','ProjectGroupMeta؛ PageMeta؛ ProjectGalleryScreenKt','كل صورة EditorPage مستقلة في LibraryStore','نموذج مشروع/فصل متعدد الصفحات مع ترتيب وإعادة ترتيب وفتح الصفحة المطلوبة','1')
A('المشاريع والصفحات','اختيار غلاف المشروع/الصفحة','ناقص','dialog_page_options: btnOpCover','—','أداة غلاف مستقلة وتحديث بطاقة المعرض','1')
A('المشاريع والصفحات','تحديد متعدد وعمليات جماعية','ناقص','ProjectGalleryScreenKt؛ dialog_batch_rename؛ btn_bulk_export','الصور تستورد متعددًا فقط','تحديد صفحات، حذف/نقل/إعادة تسمية وتصدير المحدد','1')
A('المشاريع والصفحات','سلة المحذوفات والاسترجاع','ناقص','TrashedProjectMeta؛ نصوص trash_draft_prefix','—','سلة مشاريع ومسودات مع استرجاع/حذف نهائي','5')
A('المشاريع والصفحات','إنشاء لوحة فارغة بالمقاسات والنسب','ناقص','dialog_new_blank_project؛ لقطة 19-new-canvas','Fixture خاص بالاختبار فقط','اسم وعرض وارتفاع ونسب وخلفية ضمن منتج المستخدم','1')
A('المشاريع والصفحات','استيراد الصور من الاستوديو دون تصغير الأصل','موجود','ProjectsActivity؛ BitmapRegionDecoder','PhotoLibraryPicker؛ ImagePipeline؛ فحص 48 مليون بايت iPhone','800×15000 تحقق فعلي؛ أصول iCloud وHDR/16-bit تتطلب تحققًا منفصلًا','0')
A('المشاريع والصفحات','استيراد PNG/JPEG/HEIC وصيغ ImageIO','جزئي','ProjectsActivity image imports','ImagePipeline.importImage','PNG الأصلي ينسخ؛ غير PNG يتحول إلى PNG. الصيغ/EXIF/اللون كلها لم تتحقق','1')
A('المشاريع والصفحات','استيراد PDF إلى صفحات','ناقص','dashboard_progress_converting_pdf؛ ProjectsActivity intents','—','اختيار PDF وتحويل كل صفحة بالمقاس المطلوب إلى الفصل','1')
A('المشاريع والصفحات','استيراد PSD بطبقاته','ناقص','Manifest PSD MIME؛ ProjectsActivity import flow','PSDWriter للتصدير فقط','لا يوجد استيراد طبقات PSD أو تحويل نصوصه/مجموعاته','3')
A('المشاريع والصفحات','استيراد أرشيفات ZIP/ملفات المشروع الأصلية','ناقص','ProjectsActivity MIME/استخراج الأرشيف؛ ProjectMeta','ProjectArchive يستورد .cookies فقط','توثيق وقراءة مشروع YTyper والأرشيفات وترحيلها دون فقد الطبقات','1')
A('المشاريع والصفحات','استيراد/تصدير مشروع Cookies قابل للتعديل','موجود','export_as_project مفهوم مقابل؛ الصيغة مختلفة','ProjectArchive؛ round-trip test','هذه إضافة Cookies؛ لا تثبت توافق المشروع الأصلي','1')
A('المشاريع والصفحات','استقبال الصور والملفات من قائمة مشاركة iOS','جزئي','Manifest ACTION_SEND/SEND_MULTIPLE','CookiesApp.onOpenURL للملفات؛ لا Share Extension','استقبال مشاركة متعددة مع اختيار الفصل/المجلد','5',dependency='امتداد مشاركة iOS وتوقيع الحزمة')
A('المشاريع والصفحات','استيراد من الكاميرا/الحافظة/المسودات','جزئي','ImageSourceSelectionDialog؛ btnToolPasteImage','Photos فقط؛ نص الحافظة متاح','مصادر الصور الأخرى غير موصلة بالمحرر','2')
A('المشاريع والصفحات','دمج الصفحات وMerge Studio','ناقص','MergeStudioDialogKt؛ btnToolMergeNext','—','دمج أصل المقاسات/الطبقات وإلغاء العملية والتراجع','1')
A('المشاريع والصفحات','تقسيم الصفحة بالطول أو بالعدد','ناقص','dialog_process_pages؛ btnToolSplitPage','—','تقطيع الصورة الطويلة مع توزيع الطبقات وحفظ الأبعاد','1')
A('المشاريع والصفحات','تغيير حجم الخلفية/الصفحات الذكي','ناقص','dialog_resize_canvas؛ dialog_smart_resize','—','حفظ النسبة والتحجيم الاختياري لا يكون صامتًا','1')
A('المشاريع والصفحات','Watermark Studio وعلامة مائية دفعيًا','ناقص','WatermarkStudioDialogKt؛ dialog_watermark','—','علامة نص/صورة مع معاينة ونطاق صفحات دون تغيير الأصل','4')
A('المشاريع والصفحات','تنظيف الفصل تلقائيًا في الخلفية','ناقص','AutoCleanerService؛ dialog_process_pages','تنظيف منطقة واحدة فقط','قائمة مهام وتقدم وإلغاء ونتائج لكل صفحة','4')
A('التايبر والقنص','فصول نصية محفوظة واستيراد TXT UTF-8/UTF-16','موجود','layout_typer_panel؛ typer/w.java؛ editor/d0.java','TyperStore؛ ChapterSourceView؛ اختبار UTF16 وحفظ التقدم','نجح المستخدم؛ استيراد TXT UI من Files يحتاج سيناريو آيباد منفصلًا','2')
A('التايبر والقنص','تقسيم النص إلى أسطر أو فقرات','موجود','Prefs BUBBLE_SEPARATION_MODE؛ editor/d0.java','TranscriptParser؛ Picker الفصل','المطابقة الدقيقة لكل تنسيق وحالات الترقيم تحتاج عينات أصلية','2')
A('التايبر والقنص','نافذة فقاعات داخل المحرر مع إدراج مباشر','موجود','layout_typer_panel؛ btnTyperPasteToCanvas','TyperPanel؛ insertDialogues؛ تجربة المستخدم','التدفق موجود؛ المقاسات وترتيب كل زر لا يزالان مقارنة مستقلة','2')
A('التايبر والقنص','الفقاعات المستخدمة رمادية والتقدم محفوظ','موجود','item_typer_bubble؛ adapter used state','TyperStore usedAt/usedLayer؛ restart test؛ تجربة المستخدم','التراجع عن طبقة لا يعيد الفقاعة تلقائيًا؛ يمكن تعليمها متاحة يدويًا','2')
A('التايبر والقنص','التالي/اختيار مباشر/بحث/فلتر/إعادة التقدم','موجود','layout_typer_panel search/clear/next','TyperPanel؛ UI test 38/39','انتقال لوحة التايبر وتخصيص موضعها ومقاسها يحتاجان الإكمال','2')
A('التايبر والقنص','تحرير النص والحافظة والتصدير TXT/JSON','موجود','Typer board/clipboard/import flow','ChapterSourceView؛ TyperStore.export','JSON خاص بـCookies؛ ليس حزمة الوسوم أو المشروع الأصلي','2')
A('التايبر والقنص','وسوم الحوار والخط والنمط وعدم إدراج العناوين','جزئي','TagItem؛ TagSet؛ editor/d0.java؛ TagMiniEditorActivity','DialogueTag؛ TyperSettingsView','بعض بادئات الوسوم مدعومة؛ ليس جميع خصائص TagItem أو قواعد إزالة البادئة الأصلية','2')
A('التايبر والقنص','مجموعات وسوم متعددة وتبديل المجموعة','ناقص','Prefs dynamic_tag_sets؛ active_tag_set_id','قائمة وسوم واحدة فقط','إدارة مجموعات، فرز، استيراد/تصدير وربطها بالفصل','2')
A('التايبر والقنص','شريط الوسوم السريعة والخطوط السريعة','ناقص','layout_typer_panel quickTags/quickFonts؛ btnQuickFontAdd','الخط يحدد في إعداد الوسم فقط','اختصارات على لوحة الفقاعات وتطبيق سريع على المحدد','2')
A('التايبر والقنص','تعديل فقاعة منفردة/إضافتها وإعادة ترتيبها','جزئي','btnTyperAddBubble؛ Typer board','تحرير مصدر الفصل ثم إعادة تحليل كامل','تحرير مباشر للفقاعة مع بقاء UUID والتقدم، وإضافة/حذف/ترتيب','2')
A('التايبر والقنص','تنسيق مربع/دائرة وتغيير مقاس لوحة التايبر','ناقص','btnFormatSquare/btnFormatCircle؛ TYPER_PANEL_SIZE','لوحة ثابتة متجاوبة جزئيًا','تنسيق نص الفقاعة بحسب العرض والشكل، ومقاسات/إرساء اللوحة','2')
A('التايبر والقنص','استمرار الوسم السابق //','جزئي','editor/d0.java linkTag؛ Prefs LINK_TAG','TranscriptParser linkPrefix ثابت //','أساس القاعدة موجود؛ إعداد البادئة والبدائل العربية يحتاج مطابقة','2')
A('التايبر والقنص','القنص: تحليل الفقاعة وتحديد الأهداف بالترتيب','موجود','engine/q.java؛ view/v.java؛ layout_typer_panel','SniperDetector؛ CookiesDetectBubble؛ تجربة المستخدم','نجح المستخدم؛ اختلاف الإصدار OpenCV/النص يمنع ادعاء تطابق بكسلي','2')
A('التايبر والقنص','توزيع عدة فقاعات على أهداف القنص','جزئي','typer/w.java pasteSniperTargets','TyperStore.place targets؛ SniperDetector.fitted','تنسيق الأصل وبدء التوزيع من المحددة/تخطي العناوين يحتاجان سيناريوهات مقارنة','2')
A('التايبر والقنص','ذخيرة القنص وربط الاستحقاقات والحساب','اعتماد خادم','Prefs sniper_ammo؛ typer/w.java deductions','لا مزامنة ذخيرة/استحقاقات','واجهة وحساب رسميان؛ لا اختراع رصيد أو تجاوز عضوية','6',dependency='API رصيد/استحقاقات موثّق أو متحقق وتهيئة الحساب')
A('التايبر والقنص','نافذة عائمة فوق التطبيقات','بديل iOS','FloatingWidgetService؛ FolatingWidgetDashboard','نافذة التايبر داخل التطبيق كما وافق المستخدم','iOS لا يسمح بنافذة عامة؛ نطابق داخل التطبيق والمشاركة الممكنة','2',dependency='قيد iOS؛ البديل مقبول مسبقًا')
A('التايبر والقنص','حفظ النص في المسودات واسترجاع المهملات','ناقص','text_moved_to_drafts_trash؛ floating widget','لا أرشيف مسودات نص مماثل','تخزين نسخ وعودة للنص مع التقدم','5')
A('المحرر العام','السحب والتكبير حتى رؤية البكسلات','موجود','EditorCanvasView cached region decoder','CanvasHost zoom128؛ source cache؛ pinch tests','القيمة 12800% موجودة؛ سرعة فعلية على كل أجهزة الآيباد غير مقيسة','0')
A('المحرر العام','أبعاد أصلية وتصدير لا يعتمد على المعاينة','موجود','BitmapRegionDecoder؛ الأصل 800×15000','PixelCore/ImagePipeline؛ PNG bands؛ 48M-byte test','16-bit PNG مرفوض؛ HDR/صور أكبر/تعديل ICC تحتاج توثيقًا','0')
A('المحرر العام','الرسم المباشر والسحب/التدوير السلس','جزئي','EditorCanvasView onTouch/draw','liveInk؛ LayerInteraction؛ native tests','normal stacks تحسنت؛ drawing/complex blends fallback؛ لا نتيجة FPS فعلية عامة','0')
A('المحرر العام','شريط الأدوات يتبدل بحسب الأداة','جزئي','activity_editor text/image/shape/drawing strips','EditorView text/brush strips','النص والرسم موجودان؛ الصور والأشكال لا تملكان كل شرائط الأصل','2')
A('المحرر العام','القائمة الدائرية وتخصيص اختصاراتها','ناقص','RadialMenuTool؛ HolographicRadialMenuKt؛ RadialCustomizerSheetKt','قائمة المزيد وشريط أساسي فقط','القائمة وفتحاتها/الإيماءات والاختصارات الثمانية','5')
A('المحرر العام','التراجع والإعادة','موجود','EditorCanvasView history snapshots','EditorModel undo/redo 60 حالة','يغطي الطبقات؛ تغييرات صفحات/هندسة غير موجودة أصلًا بعد','0')
A('المحرر العام','شبكة اللوحة وإعداداتها','ناقص','activity_editor btnGrid','—','شبكة بمعاينة وتبديل دون أثر في التصدير','5')
A('المحرر العام','المحاذاة المغناطيسية Snap','ناقص','layout_snap_settings؛ SNAP_* prefs','—','مركز/حواف/طبقات وقوة الجذب وأدلة أثناء السحب','2')
A('المحرر العام','قفل الخلفية وتثبيت التحريك بيد واحدة','ناقص','btnPinBackground؛ btnToolOneHandPan؛ btnLock','طبقة الأصل immutable فقط','معنى قفل التفاعل مختلف عن حماية الملف؛ يحتاج تدفق مطابق','5')
A('المحرر العام','خلفية اللوحة وألوانها/شبكتها/صورتها وتمويهها','جزئي','dialog_canvas_background؛ CanvasBackgroundBottomSheet','خلفية سوداء ثابتة','خيارات الأصل الوظيفية؛ ألوان الهوية ثابتة حسب طلب المستخدم','5')
A('المحرر العام','وضع التركيز Zen واختصارات اللمس','ناقص','EditorActivity.toggleZenMode؛ DOUBLE_TAP_ZOOM','—','إخفاء الأدوات والعودة ونقر مزدوج قابل للتخصيص','5')
A('المحرر العام','قطارة لون من المركب النهائي','جزئي','layout_eyedropper_overlay؛ ColorPickerPanel','CanvasHost يقرأ الصورة الأصلية فقط','لا يلتقط حاليًا النص/طبقات الرسم أو العدسة المكبرة','2')
A('النصوص','إضافة وتحرير النص العربي RTL','موجود','dialog_add_text؛ layout_inline_editor؛ لقطة 24','ArabicTextEditor؛ LayerRenderer.attributed','إدخال عربي مدعوم؛ تطابق كل القياسات الأصلية غير مثبت','2')
A('النصوص','المقابض التسعة وتحريك/تدوير/تمديد/نسخ/حذف','موجود','view/v.java؛ لقطة 24-text-handles','StableCanvas handles؛ UI resize/duplicate tests','توزيع الأساس موجود؛ الحساسية والمقاسات والتفاعل الأصلي يحتاجان ضبطًا','2')
A('النصوص','محرر Inline مع لصق/نسخ/حروف كبيرة/صغيرة/تطويل وإرساء','جزئي','layout_inline_editor IDs','ArabicTextEditor؛ Typer uppercase','شريط النص المختصر في الأصل غير موجود بكل أزراره/اختياراته','2')
A('النصوص','الخطوط الأصلية واستيراد TTF/OTF واختيار الخط','موجود','FontPickerPanel؛ Arabic/English/ImportedFontsActivity','Fonts؛ FontLibraryView؛ 47 ملفًا','الملفات موجودة؛ مكتبة الأقسام/تجميعات الأصل منفصلة وغير مكتملة','3')
A('النصوص','الحجم والعرض والميل والغامق والتسطير والشطب والمحاذاة','موجود','dialog_text_format؛ TextFormatPanel','TextInspector .format؛ TextStyle','التحكم موجود؛ الخط البديل/الخطوط الاصطناعية وفروق تشكيل العربية تحتاج مقارنة','3')
A('النصوص','تنسيق كلمة/مدى محدد Rich spans','ناقص','TextSpan؛ layout_inline_editor selection actions','TextStyle.spans يخزن ويعرض جزءًا؛ لا UI لتحديد المدى','اختيار كلمة وتغيير نمطها دون تعديل بقية النص','3')
A('النصوص','تنسيق كل سطر والكشيدة والتوزيع','ناقص','dialog_text_line_format؛ TextLineFormatPanel؛ KashidaLineFormatter','—','صفوف مستقلة، تطويل عربي وقياس السطر المستهدف','3')
A('النصوص','اللون والتدرج الأساسي','جزئي','layout_color_panel؛ ColorPickerPanel','TextInspector .color؛ تدرج بلونين','يتبقى مزيد من النقاط والأنواع/المواضع والقطارة داخل اللوحة','3')
A('النصوص','تدرجات متقدمة وتفاعلية وGradient Map','ناقص','AdvancedGradientDialog؛ InteractiveGradientDialog؛ GradientMapPanel','بعض حقول gradient موجودة فقط','محرر نقاط وأنواع/تدرجات محسنة على اللوحة وكتالوج presets','3')
A('النصوص','حدود النص الأساسية','موجود','layout_stroke_panel؛ StrokeEditorPanel','TextInspector .stroke؛ LayerRenderer','لون وسماكة أساسيان موجودان؛ أجزاء الحدود المتقدمة منفصلة أدناه','3')
A('النصوص','حدود إضافية/تدرج حدود/أشكال حدود وقوالب','ناقص','ExtraStroke؛ StrokeShapeView؛ StrokePresetAdapter','strokeGradient مخزن دون واجهة؛ لا ExtraStroke','كل حد مستقل وترتيبه وتدرجه ومقاسه','3')
A('النصوص','خلفية النص مع استدارة/شفافية/حشو','جزئي','layout_background_panel','TextInspector .background؛ LayerRenderer','اللون والاستدارة/الشفافية موجودة؛ X/Y padding والقوالب غير مكشوفة بالكامل','3')
A('النصوص','الظل والنعومة والإزاحة والشفافية/تدرج الظل','جزئي','layout_shadow_panel؛ ShadowEditorPanel','TextInspector .shadow','الإزاحة/اللون/النعومة موجودة؛ قوالب/تدرج/تحكم opacity ليس كاملًا','3')
A('النصوص','الموضع والمحاذاة للوحة والنقل خطوة والقلب','جزئي','layout_position_panel IDs','TextInspector .position؛ handles','دوران/تحجيم؛ لا أزرار المحاذاة الستة/step/flip X-Y من اللوحة','2')
A('النصوص','تباعد الحروف والأسطر والتشكيل','جزئي','layout_spacing_panel tashkeel','TextInspector .spacing','حروف/أسطر؛ تحكم التشكيل/tashkeel غير موجود','3')
A('النصوص','الأبعاد والبروز ثلاثي الأبعاد','جزئي','layout_3d_panel؛ ThreeDEditorPanel','TextInspector .threeD و.perspective؛ TextRaster','عمق ولون وبعض دوران؛ اتجاه البروز والتغميق/القوالب غير مطابقين','3')
A('النصوص','المنظور الرباعي والشبكة الحرة على الصورة','جزئي','layout_perspective_panel؛ view handlers','GeometryInspector؛ TextRaster','المقابض في معاينة لوحة مستقلة؛ شبكة ثابتة 3×3 ولا تحكم الأصل الكامل','3')
A('النصوص','التشويه Warp كأداة مستقلة','جزئي','layout_warp_panel؛ WarpEditorPanel','TextEffect.warp تقريب ميل','ليست خوارزمية/واجهة تشويه الأصل بالكامل','3')
A('النصوص','الخامات: استيراد وتحجيم ودوران وإزاحة','جزئي','layout_texture_panel؛ TextureEditorPanel','TextInspector .texture؛ TextRaster','الأدوات الأساسية موجودة؛ شاشة النقل والقوالب/التطبيق البكسلي غير متطابقة','3')
A('النصوص','شفافية النص الداخلية ومزج الطبقة','جزئي','layout_opacity_panel innerOpacity؛ LayerBlendMode','Layer.opacity وBlend، خمسة أوضاع الأصل ضمن ثمانية','لا فصل كامل للشفافية الداخلية عن الخارجية','3')
A('النصوص','تلاشي باتجاه/مدى كأداة مستقلة','جزئي','layout_fade_panel','TextEffect.fade opacity','التلاشي العام ليس تدرج تلاشي الأصل بالزاوية والمدى','3')
A('النصوص','المسطرة والتوسيط السحري','ناقص','layout_ruler_panel؛ btnAutoCenter','—','قياس واكتشاف المركز/threshold وإظهار الأدلة','2')
A('النصوص','تحويل النص إلى PNG/طبقة صورة','ناقص','activity_editor btnTextToPng','التصدير يرستر النص لكن لا تحويل داخلي','تحويل اختياري داخل المشروع مع أصل قابل للرجوع','3')
A('النصوص','مسح/استرجاع النص بقناع مرسوم','ناقص','layout_eraser_panel rbErase/rbRestore/showMask','قناع دائري فقط في TextInspector .mask','فرشاة قناع قابلة للمسح/الاسترجاع ومعاينة واعتماد وإلغاء','3')
A('الأنماط والخطوط','أنماط نص محفوظة وإنشاء نمط من المحدد','ناقص','TextStylesPanel؛ btnSaveCurrentStyle؛ SavedTextStyle','أربعة presets ثابتة فقط','تخزين فعلي ومجموعات وبحث وأسماء ومشاركة وإدارة','3')
A('الأنماط والخطوط','استيراد/تصدير حزم أنماط ووسوم','ناقص','ImportedStylesActivity؛ exportStylesPackage؛ tags export','JSON الفصل فقط','صيغة الأصل/Fonts toggle ومعاينة قبل الاستيراد','3')
A('الأنماط والخطوط','قطارة النمط ونسخ آخر نمط','ناقص','Radial STYLE_PIPETTE؛ btnInlineLastStyle','—','نقل خصائص النص/الخط حسب خيارات الأصل','3')
A('الأنماط والخطوط','مكتبة خطوط عربية/إنجليزية/مستوردة بفلاتر ومجموعات','جزئي','FontLibraryActivity؛ FontsGridScreenKt','FontLibraryView قائمة واحدة واستيراد؛ البحث في منتقي الخط بالمحرر','أقسام وتحديد متعدد ومفضلة/مجموعات ومعاينات تفصيلية تحتاج إعادة بناء','3')
A('الأنماط والخطوط','تصدير الخطوط/حزمها وحذف المخصصة','ناقص','ImportedFontsActivity export/import flows','FontLibraryView يستورد فقط؛ الإزالة عند فشل التسجيل ليست أداة حذف','حذف الخطوط المخصصة وتصدير حزم ومجموعات واستيراد ZIP غير موجود','3')
A('الأنماط والخطوط','مزامنة الخطوط والأنماط وGoogle Drive','اعتماد خادم','ImportedFonts/Styles syncStyleToDrive/syncAll؛ dialog_cloud_manager','—','OAuth Drive الرسمي ومجلدات التطبيق ومزامنة/استرجاع التعارض','6',dependency='Google OAuth scopes وDrive إعداد مالك الخدمة')
A('الصور والأشكال','إضافة صورة كطبقة مع حفظ المصدر','موجود','btnToolImage؛ ImageSourceSelectionDialog','EditorView PhotoLibraryPicker؛ ImagePipeline','اختيار الصور موجود؛ ليس جميع مصادر الأصل','2')
A('الصور والأشكال','موضع الصورة/دورانها/تمديدها/نسخها وحذفها','جزئي','btnImgPosition؛ view transforms','CanvasHost handles','المقابض تعمل؛ لوحة الصورة المستقلة وخطواتها ناقصة','2')
A('الصور والأشكال','قص الصورة/قص الخلفية والشفاء بقصّ المنطقة','ناقص','ImageCropActivity؛ HEAL_CROP؛ btnToolCropBg','—','قص مستطيل/منطقة ومعاينة ودمج موضع الصورة والطبقات','2')
A('الصور والأشكال','استبدال الخلفية وتغيير مقاسها','ناقص','btnReplaceBackground؛ btnImgResize؛ dialog_resize_canvas','—','استبدال مضبوط وعدم فقد مواضع الطبقات دون سؤال مناسب','1')
A('الصور والأشكال','منظور الصورة وعتامتها ومزجها','جزئي','btnImgPerspective/btnImgOpacity','opacity/blend في Layers؛ transform handles','المنظور مخزن بنمط النص وليس مسار صورة مطابقًا','3')
A('الصور والأشكال','سطوع/تباين/تشبع/تعريض/حرارة/صبغة/ظل/إضاءة/درجة/حواف','ناقص','layout_image_adjustments_panel 10 parameters','—','تعديلات غير مدمرة مع إعادة ضبط وكل قيمة مستقلة','4')
A('الصور والأشكال','فلاتر الصورة وقوالبها','ناقص','ImageFiltersPanel؛ item_filter_preset','—','كتالوج وقوة وتأثير/ترتيب مطابق المصدر','4')
A('الصور والأشكال','تأثيرات الصورة: 13 نوعًا مع تكديس وترتيب/تعطيل','ناقص','ImageEffectType؛ ImageEffectsPanel؛ item_active_effect','—','Blur/Chromatic/Glitch/Vignette/Grain/Glow/Pixelate/Halftone/Slice/Fade/Duotone/Mirror/Outline','4')
A('الصور والأشكال','الفرشاة السحرية: مؤثر موضعي بقناع','ناقص','layout_magic_brush_panel 7 types','—','Blur/Liquid/Pixelate/B&W/Glitch/Sharpen/Duotone بقناع وحجم وشفافية','4')
A('الصور والأشكال','مسح واسترجاع الصورة بقناع','ناقص','btnImgEraser؛ EraserEditorPanel','قناع دائري فقط؛ ممحاة الرسم مختلفة','قناع غير مدمر شامل وحفظه في المشروع','3')
A('الصور والأشكال','مسودات الصور وإدارة المحفوظات','ناقص','ImageDraftsBottomSheet؛ dialog_image_drafts','—','اختيار/بحث/حذف/حفظ من النصوص والصور','5')
A('الصور والأشكال','الأشكال وفقاعات الكلام الأساسية','جزئي','ShapeType 21؛ dialog_shape_picker','ShapeSheet 20؛ LayerRenderer.shapePath','الأشكال الأساسية موجودة؛ CustomPath غير موجود والمعادلات ليست مقارنة بكسلية','3')
A('الصور والأشكال','أدوات الأشكال: لون/موضع/منظور/مسح/شفافية','جزئي','activity_editor shape strip','المقابض والطبقات؛ لا شريط شكل مستقل','أدوات تحرير نوعية ومقابض المنظور والقناع','3')
A('الرسم والتنظيف','فرشاة صلبة/مائية/مضيئة وحجم ولون','موجود','DrawingBrushPanel NORMAL/WATERCOLOR/NEON','BrushSheet؛ liveInk؛ drawing tests','الرسم مباشر الآن؛ حساسية الضغط وحدود الأداء تحتاج قياسًا','0')
A('الرسم والتنظيف','فرشاة SOFT/MARKER/CUSTOM_TEXTURE','ناقص','BrushStyle enum؛ DrawingBrushPanel','—','قلم ناعم وقلم تحديد وخامة مخصصة، وليس تبديل اسم الفرشاة فقط','4')
A('الرسم والتنظيف','شفافية الفرشاة وفرشاة Plus','ناقص','layout_drawing_brush_panel opacity؛ DrawingBrushPlusPanel','opacity الطبقة فقط','شفافية مستقلة للضربة/قلم متقدم حسب خوارزمية الأصل','4')
A('الرسم والتنظيف','ممحاة الرسم ومسح اللوحة','جزئي','DrawingEraserPanel clearCanvas','erase strokes؛ معاينة متقطعة حتى رفع الإصبع','مسح حي حقيقي وتفريغ الطبقة مع تراجع، مع عرض الصحيح بين الطبقات','4')
A('الرسم والتنظيف','الرسم: مستطيل/دائرة/خط مستقيم وتعبئة','ناقص','DrawingTool enum؛ DrawingShapesPanel','Shape layers مختلفة؛ ليست نفس وضع الرسم','رسم الأشكال ضمن طبقة الرسم مع stroke/fill وundo','4')
A('الرسم والتنظيف','طمس Smudge وحجم وقوة','ناقص','DrawingSmudgePanel؛ DrawingTool.SMUDGE','—','مؤثر حي يحترم القناع/حدود الصورة ولا يغير الأصل','4')
A('الرسم والتنظيف','دلو التعبئة Fill Bucket','ناقص','RadialMenuTool.FILL_BUCKET؛ EditorCanvasView.fillBucketAt','—','تعبئة مناطق مغلقة بتسامح ولون وتراجع','4')
A('الرسم والتنظيف','تنظيف منطقة OpenCV Inpaint','موجود','QUICK_CLEANER؛ layout_inpaint_panel','CookiesInpaint Telea ROI؛ native cleaner test','المنطقة تعمل؛ إصدار OpenCV يختلف وتطابق الخوارزمية/الألوان لم يُقاس','2')
A('الرسم والتنظيف','معاينة التنظيف/تنويعات/اعتماد/إلغاء','جزئي','layout_inpaint_variations_panel؛ cleaner pill','stroke cleaner يبدأ فور الإنهاء؛ لا عدة variations','عملية مرحلية قابلة للمعاينة والإلغاء واختيار التنويع','4')
A('الطبقات','طبقات نص/صورة/شكل/رسم منفصلة','موجود','LayerData/TextLayer/ImageLayer/ShapeLayer/DrawingLayer','EditorLayer؛ LayerSheet','نموذج قابل للتعديل موجود؛ الأسماء/خصائص الأنواع الإضافية تختلف','3')
A('الطبقات','ترتيب/إظهار/إخفاء/قفل/نسخ/حذف/شفافية/مزج','موجود','dialog_layers_glass؛ item_layer','LayerSheet؛ EditorModel','الوظائف الأساسية موجودة؛ التحديد المتعدد والجمع ليسا ضمنها','3')
A('الطبقات','فلاتر أنواع الطبقات ومعاينة مكبرة/تحديد متعدد','ناقص','dialog_layers_glass؛ dialog_preview_layer','List موحدة؛ صور مصغرة للرسم غير مكتملة','تصنيف/تحديد/معاينة وترتيب نفس الأصل','3')
A('الطبقات','دمج طبقات/تسطيح/تجميع','ناقص','EditorCanvasView layer merge؛ quick merge','—','الدمج مع الحفاظ على الناتج والمزج واسترجاع الحالة','3')
A('القراءة','قارئ صورة مستقلة بتكبير لا يغير المحرر','موجود','ReaderActivity؛ activity_reader','ReaderView؛ separate viewport test','هذه قراءة صفحة واحدة فقط','1')
A('القراءة','Reader Studio: عدة صفحات واتجاه تقليب وتعديل','ناقص','ReaderStudioDialogKt؛ reader_edit_text/nudge/move','—','التنقل عبر الفصل والأدوات المصغرة وحفظ موضع القراءة','1')
A('سحب الفصل','فتح رابط فصل داخل متصفح واستخراج الصور','ناقص','WebtoonScraperActivity؛ WebtoonScraperScreenKt','—','WKWebView مع معاينة صور مستخرجة مرتبة؛ المحتوى المصرح للمستخدم','1',accept='رابط اختبار معلوم وصور متأخرة التحميل؛ لا نزول في الأبعاد ولا إعلانات ضمن الفصل')
A('سحب الفصل','تمرير تلقائي وتحميل كسول/خلفيات الصور','ناقص','WebtoonScraperActivity$startFastDownload$1؛ m.java','—','رصد صور DOM/data-src/background وترتيبها وإيقاف التمرير','1')
A('سحب الفصل','معاينة/اختيار/حذف/ترتيب الصور قبل التنزيل','ناقص','ScrapedImage؛ item_scraper_image؛ ScrapedResultsPanel','—','اختيار محدد/كل الصور بأبعادها وعرض الترتيب','1')
A('سحب الفصل','تنزيل الفصل والتقدم/إلغاء وإعادة فشل واستيراده','ناقص','WebtoonDownloadService؛ scraper state','—','حفظ الملفات باسم مرتب داخل فصل، تقدم، إلغاء، إعادة طلبات فاشلة','1',dependency='قيود iOS للتنزيل بالخلفية؛ وصول المصدر المسموح')
A('التصدير','PNG بالأبعاد الأصلية دون فقد وضغط معاينة منفصل','موجود','ExportStudio/PNG export','ImagePipeline exportPNG؛ PixelCore؛ native pixel tests','اختبار الصور المعتادة نجح؛ كامل HDR/16-bit أكبر من الحد يتطلب سياسة','0')
A('التصدير','JPEG وجودته','موجود','ExportStudioScreenKt formats','ExportSheet؛ exportJPEG native test','JPEG فيه فقد ويحمّل صورة كاملة؛ تحسين الذاكرة مطلوب للفصول الأضخم','4')
A('التصدير','PSD بطبقات مرسومة منفصلة','موجود','ExportStudio PSD export','PSDWriter؛ native PSD test','النص مرستر؛ ليس Type Layer قابلًا للتعديل في Photoshop','3')
A('التصدير','تصدير مشروع قابل للتعديل','جزئي','export_as_project؛ ExportStudio','ProjectArchive .cookies','صيغ Cookies مدعومة؛ توافق YTyper لم ينفذ','1')
A('التصدير','تصدير صفحات محددة/الكل وإعادة تسمية وحزمة','ناقص','ExportStudioScreenKt؛ dialog_batch_rename؛ item_export_page','صفحة واحدة فقط','تقدم دفعي وحزمة ZIP واختيار الصفحات والاسم والامتداد','1')
A('التصدير','تصدير ذكي بدمج الفصل وإعادة تقطيعه','ناقص','smart_export_hint؛ ExportStudio','—','يحتاج نموذج فصل ودمج/تقسيم مع طبقات ومقاس صحيح','1')
A('التصدير','حفظ مباشر إلى Photos/الملفات/المشاركة','جزئي','export save destination','ShareLink system share sheet','مشاركة موجودة؛ زر حفظ Photos مباشر وتأكيد الإتمام ليسا كاملين','1')
A('المجتمع والملف','قائمة المنشورات/تفاصيل/بحث/تحديث','موجود','CommunityActivity؛ CommunityScreenKt','ServiceHub؛ CommunityDetail؛ تجربة المستخدم','البحث محلي في 50 منشورًا؛ لا ترقيم صفحات/كل أقسام الأصل','5')
A('المجتمع والملف','قراءة التعليقات وإرسال تعليق','موجود','PostCommentInsert؛ Community comment UI','CommunityDetail.submit؛ تجربة المستخدم نجحت','الاعتماد على اعتماد التعليق/الخادم؛ الردود المتفرعة وإدارته ليست كاملة','5')
A('المجتمع والملف','الإعجاب/التصويت على المنشور','جزئي','CommunityScreenKt؛ service vote','CommunityDetail.vote','طلب فعلي؛ لم يؤكد المستخدم التصويت ولم تختبر العودة/التكرار','5')
A('المجتمع والملف','إنشاء منشور وإرفاق صور/ملفات/وسوم','ناقص','CreatePostActivity؛ activity_create_post','—','تكوين منشور ورفع صور/مرفقات مع قيود النقاط والاعتماد','5',dependency='خدمة النشر/Storage والرصد الأصلي')
A('المجتمع والملف','تعديل/حذف منشور وتعليق/إبلاغ ومشاركة','ناقص','report_post_title؛ CommunityScreenKt menus','—','صلاحيات صاحب المحتوى/مراجعة البلاغ/روابط المشاركة','5',dependency='API الصلاحيات الرسمية')
A('المجتمع والملف','أقسام الأحدث/الرائج/المثبت/إعلانات/وسائط متعددة','جزئي','CommunityScreenKt؛ media_urls؛ is_pinned','قائمة مع مثبت وصورة أولى فقط','تبويبات وترتيب وترقيم وCarousel ومرفقات وتنزيلها','5')
A('المجتمع والملف','تجديد/تمويل المنشور مقابل نقاط','اعتماد خادم','bump_post_action 10 points؛ promote_post_action 5 points','—','الواجهات والخصم الرسمي والصلاحيات','6',dependency='RPC نقاط وتمويل/تجديد رسمي')
A('المجتمع والملف','ملف شخصي: الاسم والصورة والعضوية والنقاط والفقاعات','جزئي','dashboard profile stats؛ vw_user_profiles','ProfileView؛ اختبار HTTP ملف free','عرض أساسي؛ ترتيب/أوسمة/سجل/تعديل بيانات الملف ومطابقة الواجهة ناقص','5')
A('المجتمع والملف','قائمة المتصدرين والموسم والإحصاءات','ناقص','LeaderboardScreenKt؛ leaderboard_title؛ season_bubbles','—','شاشة ترتيب/مواسم/إحصاءات وربط البيانات','6',dependency='API الترتيب والمواسم')
A('المجتمع والملف','المكافآت اليومية/المواظبة/الدعوات','ناقص','DailyRewardsScreenKt؛ InviteScreenKt؛ لقطة Rewards05','—','صفحات وتدفقات رسمية وإثبات الاستحقاق؛ دون رصيد محلي مزيف','6',dependency='RPC مكافآت ودعوات رسمي')
A('المجتمع والملف','متجر نقاط/ثيمات/أدوات/اشتراكات/فرق/إعلانات','اعتماد خادم','StoreActivity؛ StoreScreenKt؛ Store schema','—','واجهة المتجر وإثبات مشتريات iOS/الاشتراك وربط الفريق بالخدمة','6',dependency='مالك الخدمة؛ App Store/IAP؛ ربط الاستحقاقات')
A('السحابة والإشعارات','مشاريع سحابية رفع/عرض/تنزيل/حذف/حدود التخزين','اعتماد خادم','dialog_cloud_manager؛ ProjectsActivity loadProjectFromDrive','—','توافق مشروع وحساب Drive ونطاق صلاحيات وسياسة مزامنة','6',dependency='OAuth Drive الرسمي وتوثيق/اختبار صيغة المشروع')
A('السحابة والإشعارات','مزامنة الإعدادات والوسوم/الخطوط/الأنماط','اعتماد خادم','pushSettingsToCloud؛ AUTO_SYNC_FONTS/STYLES','كل التفضيلات محلية','فهم شكل البيانات والتعارض وسجل آخر مزامنة والإلغاء','6',dependency='API وخدمات الحساب الأصلية')
A('السحابة والإشعارات','إشعارات FCM/أحداث الخدمة وتنزيلات الخلفية','اعتماد خادم','Manifest FirebaseMessagingService؛ download service','—','APNs/FCM iOS وتهيئة Backend وتوقيع/Entitlements','6',dependency='إعداد APNs/Firebase لدى مالك الخدمة')
A('الإعدادات والتصميم','العربية RTL والأسود الزجاجي/أبيض/ذهبي','موجود','هوية YTyper الأصلية تتغير حسب طلب المستخدم','CookiesInterface؛ Glass؛ user preference','توجد نقاط تحكم منظور ذهبية؛ يجب تدقيق قاعدة اللون في كل حالة','5')
A('الإعدادات والتصميم','إعدادات الفصل/الوسوم/الحجم الافتراضي للنص','جزئي','SettingsActivity؛ BUBBLE_SEPARATION_MODE؛ TEXT_SIZE','TyperSettingsView؛ DialogueTagView','أساس وظيفي؛ مجموعات واستيراد الوسوم وكامل خصائصها ناقص','2')
A('الإعدادات والتصميم','مقاسات UI/أيقونات/شريط/نص/مقابض/كثافة لوحة','ناقص','Prefs UI_SCALE/ICON_SCALE/TOOLBAR_SCALE/TEXT_SCALE/HANDLE_SCALE/PANEL_DENSITY','dynamicType فقط','تحجيم آمن وPreview/Reset دون خروج العناصر على الآيباد أو الوضع الأفقي','5')
A('الإعدادات والتصميم','سرعة المقابض/مقاس إدراج التايبر/نقر مزدوج/SmartPosition','ناقص','HANDLE_TRANSFORM_SPEED؛ TYPER_PASTE_SCALE؛ SMART_TEXT_POSITIONING','حساسية ثابتة؛ viewport placement','كل إعداد يجب أن يغير السلوك ويستمر بعد إعادة الفتح','2')
A('الإعدادات والتصميم','اتجاه القارئ/جودة المعاينة/دقة اللوحة/المنظف الذكي','ناقص','PAGE_TURN_DIRECTION؛ canvas_resolution؛ SMART_CLEANER','Preview sample تلقائي؛ إعدادات ثابتة','ضبط معاينة آمن مع توضيح عدم تغيير دقة الأصل','5')
A('الإعدادات والتصميم','لغة التطبيق ومظهره/الخلفيات/تخصيص الثيم','جزئي','dialog_language؛ Prefs theme/background','عربية وDark ثابتان حسب طلب المستخدم','الهوية ثابتة عمدًا؛ خيارات وظيفية للتكبير/القراءة تبقى؛ ليست مطابقة كل ثيمات المتجر','5')
A('الإعدادات والتصميم','حركات/انتقالات/استجابة الضغط/دعم Reduce Motion','جزئي','Compose theme/animations/dashboard cards','SwiftUI transitions؛ glass buttons','يلزم مقارنة نوع الانتقال وتخفيف الحركة، خصوصًا القوائم وحالات التحميل','5')
A('الإعدادات والتصميم','تعامل الأخطاء/التعافي/تقرير الانهيار','جزئي','CrashReportActivity؛ ToastManager؛ cancel dialogs','alerts؛ some loading/cancel states','حالات فقد الشبكة/امتلاء التخزين/فشل جزئي/انهيار واستعادة العمل غير كاملة','0')
A('التحقق','اختبارات طويلة الصور وPhotos والطبقات والنص/التايبر','جزئي','سلوك المرجع ولقطاته؛ شروط المستخدم','27 اختبار iPhone كاملًا؛ 26 نجاح و1 فشل iPad؛ user manual','فشل iPad توقيت تهيئة cache قبل القراءة الأولى؛ التحقق يحتاج انتظار readiness بدل زمن ثابت. لا دليل تلف source','0',accept='اجتياز iPad وiPhone بلا اعتماد على sleeps ثابتة مع فحص كل البايتات؛ قياس جهاز فعلي')
A('التحقق','المطابقة البصرية والسلوكية لكل واجهة وزر','غير متحقق','219 layout XML؛ 110 خاصة بالتطبيق؛ Compose/programmatic','54 لقطة لكل محاكي؛ لقطات أصل غير موثقة لكل حالة مصادقة','الفهرس ثابت/شامل الموارد المختارة؛ ليس تصويرًا كاملًا لكل حساب/ميزة مدفوعة. يلزم سيناريوهات لكل صف','0')

# Enumerated effects get separate rows so an umbrella panel cannot hide them.
cat=json.loads((out/'original-tool-catalog.json').read_text())
for effect in cat['TextEffect']:
 if effect=='NONE':continue
 native={'BLUR','GLITCH','SLICE','NEON','FADE','WARP','SHADOW','ERROR'}
 A('كتالوج تأثيرات النص',effect,'جزئي' if effect in native else 'ناقص','data/model/TextEffect.java؛ EffectsEditorPanel','TextEffect/TextRaster' if effect in native else '—','النوع الأساسي موجود لكن تطابق خوارزمية/قيم/معاينة الأصل غير مثبت' if effect in native else 'نوع غير موجود في محرك أو واجهة iOS','3')
for effect in cat['ImageEffectType']:
 A('كتالوج تأثيرات الصور',effect,'ناقص','data/model/ImageEffectType.java؛ ImageEffectsPanel','—','نوع مستقل مع معلمات وقناع/ترتيب وإعادة ضبط؛ توفره في الأصل يتطلب تحققًا للحساب','4')
with (out/'feature-parity.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows(rows)
(out/'feature-parity.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
counts=collections.Counter(r['status'] for r in rows)
(out/'audit-summary.json').write_text(json.dumps({'source_commit':'25d6f9f50832f0f1c22e2f49ca878ad520ed126f','reference_version':'4.5','comparison_items':len(rows),'functional_status_counts':dict(counts),'not_a_parity_percentage':True,'user_manual_evidence':{'email_password_login':'passed by user','community_comment':'passed by user','typer':'passed by user','sniper':'passed by user','google':'not tested by user; localhost dependency unresolved'},'ci':{'run':37951150601,'package':'passed','iphone_full_suite':{'passed':27,'failed':0},'ipad_full_suite':{'passed':26,'failed':1,'failure':'fixed-delay cache-read readiness assertion'},'iphone_photos_bytes':48000000,'iphone_photos_pixels_unchanged':True,'ipad_extra_photos_integrity':'not run after failed full suite'}},ensure_ascii=False,indent=2)+'\n')
md=['# جرد المقارنة: YTyper 4.5 وCookies Editor للآيفون والآيباد','',f'هذه مصفوفة من **{len(rows)} بند مقارنة**، وليست نسبة اكتمال. «موجود» يعني أن الوظيفة الأساسية موجودة، ولا يعني تطابق الشكل أو جميع الحالات الطرفية. «جزئي» يحتاج استكمالًا. «اعتماد خادم» يحتاج تهيئة/استحقاقات رسمية؛ ليس وصفًا لزر يمكن تشغيله محليًا.','', 'مرجع iOS: `25d6f9f50832f0f1c22e2f49ca878ad520ed126f`. مرجع Android: YTyper 4.5 (ملف APK الذي قدمته). تفاصيل كل بند، مصدره، اعتماديته واختبار قبوله في [CSV](feature-parity.csv) و[JSON](feature-parity.json).','','تجربتك اليدوية: نجح الدخول **بالبريد وكلمة المرور** والتعليق في المجتمع والتايبر والقنص. Google ليس ضمن هذا الإثبات.','','| الحالة الوظيفية | عدد البنود |','|---|---|']+[f'| {s} | {n} |' for s,n in counts.items()]
for group in dict.fromkeys(r['group'] for r in rows):
 md+=['',f'## {group}','', '| رقم | الوظيفة | حالة الآيفون | الباقي | المرحلة |','|---|---|---|---|---|']
 for r in rows:
  if r['group']==group:md.append('| '+ ' | '.join(r[k].replace('|','/') for k in ['id','feature','status','gap','phase'])+' |')
(out/'comparison-ar.md').write_text('\n'.join(md)+'\n')
print('comparison_items',len(rows),'counts',dict(counts))
